### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by devCrossNet**
### What is accomplished by your PR?
this PR updates the `@vuesion/service`, `@vuesion/addon-contentful`, `@vuesion/addon-vuex-persist` and the package dependencies. I tested the new packages locally by publishing it to a local registry and testing every task in the vuesion project.

### Is there something controversial in your PR?
I didn't update `storybook-addon-vue-info` because it would be a breaking change

### Link to the Issue
no ticket

# Checklist

### New Feature / Bug Fix

- [x] Run unit tests to ensure all existing tests are still passing
- [ ] Add new passing unit tests to cover the code introduced by your PR

### CODE REVIEW

**Comment by devCrossNet** [comment]
Unfortunately, storybook only declares it as a peer dependency. Afaik, that means you have to take care to add it to the projects dependencies. Never tried it without it.

Should we give it a try?

**Comment by MohitTilwani15** [comment]
I am using storybook in my project which is using Vue, and I didn't have to take care of it. I would say we can give it a shot 😊

**Comment by devCrossNet** [comment]
I am not quite sure. This post says peer dependencies are not installed automatically: https://stackoverflow.com/questions/35207380/how-to-install-npm-peer-dependencies-automatically

**Comment by MohitTilwani15** [comment]
Just checked locally, by removing `react` and `react-dom` from service and used `verdaccio` to test, storybook works like a charm.

**Comment by devCrossNet** [comment]
Did you get a peer dependency warning during npm install?

**Comment by MohitTilwani15** [comment]
No warning regarding react not being installed as peer dependency. Though received it for some other packages which I think should be taken care of

Screen Shot 2019-04-23 at 21 51 48

**Comment by devCrossNet** [comment]
@MohitTilwani15 I removed react and react-dom with success and I was also able to get rid of most of the peerDependency warnings. 

the one from `ts-jest` is complicated because it's a dependency from `vue-jest` and we have to wait for the new `vue-jest` version in order to get the latest version of `ts-jest` that uses `jest` version 24 and higher

I also moved the `ts-jest` dependency into the service so we can remove it in vuesion (PR coming)

I also removed running the clean command before prettier, we can use .prettierignore in the vuesion project to exclude the build directories

**Comment by devCrossNet** [comment]
tested with local npm registry

**Comment by MohitTilwani15** [comment]
There is one more small thing though not related to this PR but a small fix. In [base.ts](https://github.com/vuesion/packages/blob/fa461a0682e48f240c30d8f4c320b1a5b5bbbd77/packages/service/src/webpack/config/base.ts#L26) file we have alias of src and we also have that in [config.json](https://github.com/vuesion/vuesion/blob/358f41658a44517deeddae8dc7c89858a89f8d13/.vuesion/config.json#L19) in vuesion. So i guess we can remove it from base.ts file

**Comment by devCrossNet** [comment]
@MohitTilwani15 it's because I didn't want a BC break and release version 3.0. Maybe we can add a condition  if the key is not in the config

**Pull request merged**
